name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main  # O workflow será acionado quando houver um push na branch main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar as credenciais da AWS
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-1

      # 3. Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'  # Especifique a versão do Terraform

      # 4. Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Validar os arquivos Terraform
      - name: Terraform Validate
        run: terraform validate

      # 6. Aplicar a infraestrutura com Terraform
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
          echo "terraform_apply_status=Success" >> $GITHUB_ENV  # Usando Environment Files para salvar status

      # 7. Exibir o status da aplicação (opcional)
      - name: Show Terraform Outputs
        run: echo "Terraform apply completed:" ${{ env.terraform_apply_status }}

